// O'zbekiston Respublikasi Markaziy bankining tijorat banklari
// bosh ofislari ro'yxati (2026-07-06 holatiga).
export const UZBEKISTAN_BANKS = [
  "O'zmilliybank",
  'Xalq banki',
  'Asakabank',
  "O'zsanoatqurilishbank",
  'Agrobank',
  'Biznesni rivojlantirish banki',
  'Turonbank',
  'Mikrokreditbank',
  'Aloqabank',
  'Poytaxt bank',
  'Madad Invest Bank',
  'InFinBank',
  'AVO BANK',
  'TBC Bank',
  'ANOR BANK',
  'Tayanch mikromoliya banki',
  'ASIA ALLIANCE BANK',
  "Ipak Yo'li bank",
  'Kapitalbank',
  'Universal bank',
  'Trastbank',
  'Davr-bank',
  'Octobank',
  'Orient Finans bank',
  'Garant bank',
  'Hamkorbank',
  'Open bank',
  'UZUM BANK',
  'APEX BANK',
  'HAYOT BANK',
  'Tenge Bank',
  "KDB Bank O'zbekiston",
  'Ziraat Bank Uzbekistan',
  'SODEROT Bank',
  'Ipoteka-bank',
];
